### PR TITLE
Creation of Home Page using HTML , CSS , JS

### PR DESCRIPTION
**Pull request by instantboostbyabhaykeshari**
#3 
I have resolved the issue, please review it

### CODE REVIEW

**Comment by Prayas248** [comment]
@instantboostbyabhaykeshari 
- Your page is not responsive at all
- Plus, dont make the Navbar stylish, as it is not your task and please remove the dark mode for now
- Just make the design a bit more professional and responsive
- Thank You

**Comment by Prayas248** [comment]
> #3 I have resolved the issue, please review it

> @instantboostbyabhaykeshari
> 
> * Your page is not responsive at all, and please use a uniform font for the whole page, as different font usage are making it unprofessional.
> * Plus, dont make the Navbar stylish, as it is not your task and please remove the dark mode for now
> * Just make the design a bit more professional and responsive
> * Thank You

**Comment by instantboostbyabhaykeshari** [comment]
#3 I have resolved the required issue as per demand please review it.

Thank You.

**Comment by Prayas248** [comment]
@instantboostbyabhaykeshari Please dont add any JS on this page, so remove all the js in script.js and let it be a page with HTML and CSS only
- also remove the navbar that you made as it is not your issue to resolve

**Pull request merged**
